"""initial postgres schema

Revision ID: fed4daf4b842
Revises: e4f5a6b7c8d9
Create Date: 2026-10-05 10:20:31.693071

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fed4daf4b842'
down_revision = None
branch_labels = ('postgres',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('classification_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=30), nullable=False),
    sa.Column('pattern_value', sa.Text(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classification_rules_pattern_type', 'classification_rules', ['pattern_type'], unique=False)
    op.create_index('ix_classification_rules_priority', 'classification_rules', ['priority'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_lease_expires_at', 'jobs', ['lease_expires_at'], unique=False)
    op.create_index('ix_jobs_state_kind', 'jobs', ['state', 'kind'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('completeness_declared', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('executed_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_token')
    )
    op.create_index('ix_import_batches_account_hash', 'import_batches', ['account_id', 'file_hash'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('classification_source', sa.String(length=50), nullable=True),
    sa.Column('classification_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'date'], unique=False)
    op.create_index('ix_transactions_category_date', 'transactions', ['category_id', 'date'], unique=False)
    op.create_index('ix_transactions_merchant_date', 'transactions', ['merchant', 'date'], unique=False)
    op.create_index('ix_transactions_type_date', 'transactions', ['transaction_type', 'date'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('review_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classifications_review_state', 'classifications', ['review_state'], unique=False)
    op.create_index('ix_classifications_transaction', 'classifications', ['transaction_id'], unique=False)
    op.create_table('source_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_date', sa.String(length=20), nullable=False),
    sa.Column('raw_category', sa.String(length=255), nullable=False),
    sa.Column('raw_subcategory', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_amount', sa.String(length=30), nullable=False),
    sa.Column('raw_balance', sa.String(length=30), nullable=True),
    sa.Column('raw_status', sa.String(length=20), nullable=False),
    sa.Column('raw_reconciled', sa.String(length=10), nullable=False),
    sa.Column('parsed_date', sa.Date(), nullable=True),
    sa.Column('parsed_amount_cents', sa.Integer(), nullable=True),
    sa.Column('parsed_balance_cents', sa.Integer(), nullable=True),
    sa.Column('parsed_status', sa.String(length=20), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_observations_batch', 'source_observations', ['batch_id'], unique=False)
    op.create_index('ix_source_observations_transaction', 'source_observations', ['transaction_id'], unique=False)
    op.create_table('transfer_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_a_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_b_id', sa.String(length=36), nullable=False),
    sa.Column('confirmed_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('transaction_a_id < transaction_b_id', name='ck_transfer_links_order'),
    sa.ForeignKeyConstraint(['transaction_a_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['transaction_b_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_a_id', 'transaction_b_id', name='uq_transfer_links_pair')
    )
    op.create_index('ix_transfer_links_transaction_a', 'transfer_links', ['transaction_a_id'], unique=False)
    op.create_index('ix_transfer_links_transaction_b', 'transfer_links', ['transaction_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transfer_links_transaction_b', table_name='transfer_links')
    op.drop_index('ix_transfer_links_transaction_a', table_name='transfer_links')
    op.drop_table('transfer_links')
    op.drop_index('ix_source_observations_transaction', table_name='source_observations')
    op.drop_index('ix_source_observations_batch', table_name='source_observations')
    op.drop_table('source_observations')
    op.drop_index('ix_classifications_transaction', table_name='classifications')
    op.drop_index('ix_classifications_review_state', table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('ix_transactions_type_date', table_name='transactions')
    op.drop_index('ix_transactions_merchant_date', table_name='transactions')
    op.drop_index('ix_transactions_category_date', table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_import_batches_account_hash', table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index('ix_jobs_state_kind', table_name='jobs')
    op.drop_index('ix_jobs_lease_expires_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_classification_rules_priority', table_name='classification_rules')
    op.drop_index('ix_classification_rules_pattern_type', table_name='classification_rules')
    op.drop_table('classification_rules')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
