"""initial_schema

Revision ID: 6d9b6bbbe14a
Revises: 
Create Date: 2026-10-04 12:47:20.028965

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d9b6bbbe14a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_lease_expires_at', ['lease_expires_at'], unique=False)
        batch_op.create_index('ix_jobs_state_kind', ['state', 'kind'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('completeness_declared', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('executed_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_token')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index('ix_import_batches_account_hash', ['account_id', 'file_hash'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('classification_source', sa.String(length=50), nullable=True),
    sa.Column('classification_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_date', ['account_id', 'date'], unique=False)
        batch_op.create_index('ix_transactions_category_date', ['category_id', 'date'], unique=False)
        batch_op.create_index('ix_transactions_merchant_date', ['merchant', 'date'], unique=False)
        batch_op.create_index('ix_transactions_type_date', ['transaction_type', 'date'], unique=False)

    op.create_table('classifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('rule_version', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('review_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.create_index('ix_classifications_review_state', ['review_state'], unique=False)
        batch_op.create_index('ix_classifications_transaction', ['transaction_id'], unique=False)

    op.create_table('source_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_date', sa.String(length=20), nullable=False),
    sa.Column('raw_category', sa.String(length=255), nullable=False),
    sa.Column('raw_subcategory', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_amount', sa.String(length=30), nullable=False),
    sa.Column('raw_balance', sa.String(length=30), nullable=True),
    sa.Column('raw_status', sa.String(length=20), nullable=False),
    sa.Column('raw_reconciled', sa.String(length=10), nullable=False),
    sa.Column('parsed_date', sa.Date(), nullable=True),
    sa.Column('parsed_amount_cents', sa.Integer(), nullable=True),
    sa.Column('parsed_balance_cents', sa.Integer(), nullable=True),
    sa.Column('parsed_status', sa.String(length=20), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_observations', schema=None) as batch_op:
        batch_op.create_index('ix_source_observations_batch', ['batch_id'], unique=False)
        batch_op.create_index('ix_source_observations_transaction', ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_source_observations_transaction')
        batch_op.drop_index('ix_source_observations_batch')

    op.drop_table('source_observations')
    with op.batch_alter_table('classifications', schema=None) as batch_op:
        batch_op.drop_index('ix_classifications_transaction')
        batch_op.drop_index('ix_classifications_review_state')

    op.drop_table('classifications')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_type_date')
        batch_op.drop_index('ix_transactions_merchant_date')
        batch_op.drop_index('ix_transactions_category_date')
        batch_op.drop_index('ix_transactions_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batches_account_hash')

    op.drop_table('import_batches')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_state_kind')
        batch_op.drop_index('ix_jobs_lease_expires_at')

    op.drop_table('jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_entity')
        batch_op.drop_index('ix_audit_events_created_at')

    op.drop_table('audit_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
